spring:
  application:
    name: pl-rules
  boot:
    admin:
      client:
        url: http://localhost:1111
  profiles:
    active:
    - dev
server:
  servlet:
    context-path: /plrules
  port: 8082
